#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.3.{build}

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: false
# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  #- ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

# clone directory
clone_folder: c:\projects\myproject

environment:
  matrix:
  - PYTHON: C:\Python36-x64
    PYTHON_VERSION: 3.6.5
    PYTHON_ARCH: 64
  - PYTHON: C:\Python36
    PYTHON_VERSION: 3.6.5
    PYTHON_ARCH: 32

build_script:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "pyinstaller -F -w -n lapyrinthe --clean lapyrinthe.spec"

artifacts:
  - path: dist/*

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: GitHub
    description: 'Lapyrinthe'
    artifact: /.*\.exe/
    auth_token:
      secure: ZzAkDVtw2SmgOnO6xlBy5htODrHrVCiXVHi+i3/Y7QSxx04Mso1j2Mw32myY+oL4
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
