#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: false
# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - cmd: >-
    ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

    SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

# clone directory
clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: false                 # default is "false"

environment:
  matrix:
  - PYTHON: C:\Python36-x64
    PYTHON_VERSION: 3.6.5
    PYTHON_ARCH: 64

build_script:
  - cmd:>-
    pip install -r requirements.txt
    pyinstaller -F -w -n lapyrinthe --clean lapyrinthe.spec"

artifacts:
  - path: dist

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy: off

    # Deploy to GitHub Releases
  # - provider: GitHub
  #   artifact: /.*\.exe/           # upload all NuGet packages to release assets
  #   draft: false
  #   prerelease: false
  #   on:
  #     branch: master                # release from master branch only
  #     appveyor_repo_tag: true       # deploy on tag push only

#---------------------------------#
#         notifications           #
#---------------------------------#

# notifications:
#
#   # Email
#   - provider: Email
#     to:
#       - jeremy.collin.lnk@gmail.com
#     subject: 'Build {{status}}'                  # optional
#     message: "{{message}}, {{commitId}}, ..."    # optional
#     on_build_status_changed: true
