language: python
python:
  - 3.6

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.6.0
  - os: linux
    language: python
    env: PYTHON=3.6.0

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON --enable-framework
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

install:
  - pip install -r requirements.txt
script:
  - pyinstaller -F -w -n lapyrinthe --clean lapyrinthe.spec
deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "./dist/lapyrinthe"
  skip_cleanup: true
  on:
    tags: true
