language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pyinstaller -F -w -n lapyrinthe --clean lapyrinthe.spec
deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "./dist/lapyrinthe"
  skip_cleanup: true
  on:
    tags: true
